name: CHEF_Warp

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp.py
    - name: Commit and push changes
      run: |          
          git config --global user.email "milaadfarzian@gmail.com"
          git config --global user.name "miladfarzian"
          git config credential.helper store
          git add -A
          git commit -m "Automatic update"
          git push
